version: "2"
services:
  mysql-master2:
    environment:
      MYSQL_ROOT_PASSWORD: liugeyi
    hostname: mysql-master2
    image: "mysql:5.7"
    ports:
      - "3310:3306"
    tty: true
    volumes:
      - /Users/maze/Docker/mysql2/mysql-master2/config/my.cnf:/etc/mysql/my.cnf
      - /Users/maze/Docker/mysql2/mysql-master2/data:/var/lib/mysql/
    command: --default-authentication-plugin=mysql_native_password
  # mysql-slave2-1:
  #   environment:
  #     MYSQL_ROOT_PASSWORD: liugeyi
  #   hostname: mysql-slave2-1
  #   depends_on:
  #     - mysql-master
  #   image: "mysql:5.7"
  #   ports:
  #     - "3308:3306"
  #   tty: true
  #   volumes:
  #     - /Users/maze/Docker/mysql/mysql-slave2-1/config/my.cnf:/etc/mysql/my.cnf
  #     - /Users/maze/Docker/mysql/mysql-slave2-1/data:/var/lib/mysql/
  #   command: --default-authentication-plugin=mysql_native_password
  #   links:
  #     - "mysql-master:mysql-master"
  # mysql-slave2-2:
  #   environment:
  #     MYSQL_ROOT_PASSWORD: liugeyi
  #   hostname: mysql-slave2-2
  #   depends_on:
  #     - mysql-master
  #   image: "mysql:5.7"
  #   ports:
  #     - "3309:3306"
  #   tty: true
  #   volumes:
  #     - /Users/maze/Docker/mysql/mysql-slave2-2/config/my.cnf:/etc/mysql/my.cnf
  #     - /Users/maze/Docker/mysql/mysql-slave2-2/data:/var/lib/mysql/
  #   command: --default-authentication-plugin=mysql_native_password
  #   links:
  #     - "mysql-master:mysql-master"
