version: "2"
services:
    peer1:
        image: mazekkkk/microservice-discovery-eureka-multi:0.0.1
        ports:
            - "8761:8761"
        environment:
            - spring.profiles.active=peer1
    peer2:
        image: mazekkkk/microservice-discovery-eureka-multi:0.0.1
        hostname: peer2
        ports:
            - "8762:8762"
        environment:
            - spring.profiles.active=peer2
