version: "2"
services:
    redis1:
        image: redis
        container_name: my_redis
        command: bash -c "redis-server /usr/local/etc/redis.conf | redis-sentinel /usr/local/etc/sentinel.conf"
        ports:
            - "6379:6379"
            - "26379:26379"
        volumes:
            - /Users/maze/Docker/redis/slave1/data/:/data
            - /Users/maze/Docker/redis/slave1/config/redis-slave1.conf:/usr/local/etc/redis.conf
            - /Users/maze/Docker/redis/slave1/config/sentinel.conf:/usr/local/etc/sentinel.conf
    redis2:
        image: redis
        container_name: my_redis2
        command: bash -c "redis-server /usr/local/etc/redis.conf | redis-sentinel /usr/local/etc/sentinel.conf"
        ports:
            - "6380:6380"
            - "26380:26380"
        volumes:
            - /Users/maze/Docker/redis/slave2/data/:/data
            - /Users/maze/Docker/redis/slave2/config/redis-slave2.conf:/usr/local/etc/redis.conf
            - /Users/maze/Docker/redis/slave2/config/sentinel.conf:/usr/local/etc/sentinel.conf
        depends_on:
            - 'redis1'
    redis3:
        image: redis
        container_name: my_redis3
        command: bash -c "redis-server /usr/local/etc/redis.conf | redis-sentinel /usr/local/etc/sentinel.conf"
        ports:
            - "6381:6381"
            - "26381:26381"
        volumes:
            - /Users/maze/Docker/redis/slave3/data/:/data
            - /Users/maze/Docker/redis/slave3/config/redis-slave3.conf:/usr/local/etc/redis.conf
            - /Users/maze/Docker/redis/slave3/config/sentinel.conf:/usr/local/etc/sentinel.conf
        depends_on:
            - 'redis1'
    redis4:
        image: redis
        container_name: my_redis4
        command: bash -c "redis-server /usr/local/etc/redis.conf | redis-sentinel /usr/local/etc/sentinel.conf"
        ports:
            - "6382:6382"
            - "26382:26382"
        volumes:
            - /Users/maze/Docker/redis/slave4/data/:/data
            - /Users/maze/Docker/redis/slave4/config/redis-slave4.conf:/usr/local/etc/redis.conf
            - /Users/maze/Docker/redis/slave4/config/sentinel.conf:/usr/local/etc/sentinel.conf
        depends_on:
            - 'redis1'
    redis5:
        image: redis
        container_name: my_redis5
        command: bash -c "redis-server /usr/local/etc/redis.conf | redis-sentinel /usr/local/etc/sentinel.conf"
        ports:
            - "6383:6383"
            - "26383:26383"
        volumes:
            - /Users/maze/Docker/redis/slave5/data/:/data
            - /Users/maze/Docker/redis/slave5/config/redis-slave5.conf:/usr/local/etc/redis.conf
            - /Users/maze/Docker/redis/slave5/config/sentinel.conf:/usr/local/etc/sentinel.conf
        depends_on:
            - 'redis1'
    redis6:
        image: redis
        container_name: my_redis6
        command: bash -c "redis-server /usr/local/etc/redis.conf | redis-sentinel /usr/local/etc/sentinel.conf"
        ports:
            - "6384:6384"
            - "26384:26384"
        volumes:
            - /Users/maze/Docker/redis/slave6/data/:/data
            - /Users/maze/Docker/redis/slave6/config/redis-slave6.conf:/usr/local/etc/redis.conf
            - /Users/maze/Docker/redis/slave6/sentinel.conf:/usr/local/etc/sentinel.conf
        depends_on:
            - 'redis1'
